const seasons=[{name:'春天',en:'SPRING',line:'让心情，慢慢发芽',accent:'#6b805f',tint:'#eaf0df',prefix:'春日',reason:'回暖的空气里，清透花香、绿意和柔软麝香更显轻盈。让香气像刚打开的窗，留一点呼吸的空间。'},{name:'夏天',en:'SUMMER',line:'把海风，穿在身上',accent:'#637f8b',tint:'#e7eff2',prefix:'夏日',reason:'炎热时，清新绿叶、果香与空气感更容易穿得舒服。优先轻盈的气味表达，喷多少也可以随温度调整。'},{name:'秋天',en:'AUTUMN',line:'收集一捧，温柔日光',accent:'#a17d55',tint:'#f2e7d7',prefix:'秋日',reason:'微凉天气适合果香、木质与柔和暖意慢慢展开。清新与温暖之间的层次，像薄针织衫一样自然。'},{name:'冬天',en:'WINTER',line:'靠近一点，就很温暖',accent:'#82768d',tint:'#eee9f1',prefix:'冬日',reason:'冷空气里，木质、香草和绵柔花香带来包裹感。如果你更爱清爽，冬天也可以保留自己的轻盈气息。'}];
const questions=[['难得空出一个下午，你想去哪里？','凭第一直觉，选一个想待久一点的地方。','sun',['临海小路，吹一会儿风','街角花店，挑一束花','森林小屋，听树叶声','阳光客厅，窝进沙发']],['推开窗，你希望听见什么？','想象那个让你放松的瞬间。','breeze',['雨后滴答的屋檐','花园里轻轻的鸟鸣','远处安静的风声','朋友低低的谈笑']],['出门时，你会带上哪件小物？','不必考虑实用，喜欢就好。','spark',['一张还没写的明信片','一条柔软的丝带','一本翻旧了的随笔','一只温热的随行杯']],['如果今天有颜色，你会选？','把这一刻的心情，装进一张色卡。','orbit',['透明的海盐蓝','花瓣一样的雾粉','树影里的橄榄绿','烤过的奶油米']],['你想被记住的，是哪一种感觉？','不必像平时的你，也可以是想成为的你。','asterisk',['轻快自由，像一阵风','温柔灵动，让人想靠近','安静有趣，有自己的世界','松弛温暖，很让人安心']],['一天结束，最想定格哪个画面？','给今天留一个小小的结尾。','moon',['海平线上的最后一束光','桌上那束刚好盛开的花','书页上缓缓移动的树影','暖灯下，两只挨着的杯子']],['真正闻起来，你更喜欢哪一类？','这一题认真听鼻子的，它会更影响香水推荐。','flower',['清爽果香 / 柑橘 / 绿意','玫瑰 / 清透花香','干燥木质 / 草本','柔软麝香 / 香草暖香']],['香气里的甜，你喜欢多少？','没有正确答案，只选你穿着舒服的程度。','drop',['尽量少甜，清爽一点','微微甜，轻柔就好','适中的甜，很有包裹感','明显暖甜，我很喜欢']]];
const lineIcons={sun:'<circle cx="16" cy="16" r="5"/><path d="M16 3v5M16 24v5M3 16h5M24 16h5M6.8 6.8l3.6 3.6M21.6 21.6l3.6 3.6M6.8 25.2l3.6-3.6M21.6 10.4l3.6-3.6"/>',breeze:'<path d="M3 11c5-4 8 4 13 0s8-1 10 1M5 18c4-3 7 3 11 0s7-2 11 1M9 24c3-2 5 1 8 0"/>',spark:'<path d="M16 3c.8 7.6 5.4 12.2 13 13-7.6.8-12.2 5.4-13 13-.8-7.6-5.4-12.2-13-13 7.6-.8 12.2-5.4 13-13Z"/><path d="M25 3v6M22 6h6"/>',orbit:'<circle cx="16" cy="16" r="8"/><path d="M6 8c3-4 8-6 13-5M26 24c-3 4-8 6-13 5"/><circle cx="25" cy="9" r="1.4"/>',asterisk:'<path d="M16 3v26M3 16h26M6.8 6.8l18.4 18.4M6.8 25.2 25.2 6.8"/>',moon:'<path d="M23.5 24.5A12 12 0 0 1 18 2.8a10.5 10.5 0 1 0 5.5 21.7Z"/><path d="M24 7v4M22 9h4"/>',flower:'<circle cx="16" cy="16" r="2.4"/><path d="M16 13.6c-5-1-6.5-5.3-3.8-7.2 2.5-1.8 4.3 1.8 3.8 7.2Zm2.4 2.4c1-5 5.3-6.5 7.2-3.8 1.8 2.5-1.8 4.3-7.2 3.8ZM16 18.4c5 1 6.5 5.3 3.8 7.2-2.5 1.8-4.3-1.8-3.8-7.2ZM13.6 16c-1 5-5.3 6.5-7.2 3.8-1.8-2.5 1.8-4.3 7.2-3.8Z"/>',drop:'<path d="M16 3c4.5 6.4 8 10.7 8 15.2a8 8 0 0 1-16 0C8 13.7 11.5 9.4 16 3Z"/><path d="M12 19c.6 2 2 3 4 3"/>'};
function questionIcon(name){return `<svg class="question-icon-svg" viewBox="0 0 32 32" aria-hidden="true" focusable="false">${lineIcons[name]}</svg>`}
const profiles=[{name:'追风漫游者',code:'AIR',desc:'你把自由穿在身上，连路过的风都有了明亮的方向。',tags:['清透','自由','轻快']},{name:'花间来信人',code:'BLOOM',desc:'你把温柔藏进细节，不声张，也能让平凡的一天开花。',tags:['花香','温柔','灵动']},{name:'树影收藏家',code:'WOOD',desc:'你自有安静的节奏，在喧闹之外，收藏有分量的小事。',tags:['木质','沉静','自然']},{name:'暖光造梦家',code:'GLOW',desc:'你像一盏刚亮起的灯，让靠近的人慢慢卸下疲惫。',tags:['柔软','暖意','松弛']}];
const perfumes=[
['HERMÈS','尼罗河花园','Un Jardin sur le Nil EDT',['青芒果','莲花','西克莫无花果木'],0,0,[3,3,1,0],'日间出游 · 轻松通勤','像走入河畔花园，青绿果香里留着一丝水意。','https://www.hermes.com/uk/en/product/un-jardin-sur-le-nil-eau-de-toilette-V20396/', 'designer'],
['HERMÈS','绯红大黄','Eau de rhubarbe écarlate EDC',['大黄','马缨丹','麝香'],0,1,[3,3,2,1],'城市漫步 · 周末约会','带一点酸意的红色果香，像轻快咬下一口脆果。','https://www.hermes.com/us/en/product/eau-de-rhubarbe-ecarlate-eau-de-cologne-V107155V0/','designer'],
['JO MALONE LONDON','鼠尾草与海盐','Wood Sage & Sea Salt Cologne',['黄葵籽','海盐','鼠尾草'],0,0,[3,3,3,2],'日常通勤 · 海边散步','咸润空气与草本相遇，像没有目的地的海岸漫步。','https://www.jomalone.com/wood-sage-sea-salt','designer'],
['DIPTYQUE','希腊无花果','Philosykos EDT',['无花果叶','无花果木','白雪松'],2,1,[3,3,3,1],'美术馆 · 自然出游','青绿树叶下，有一小片柔软而明亮的树荫。','https://www.diptyqueparis.com/en_us/l/fragrances.html','niche'],
['DIPTYQUE','玫瑰之水','Eau Rose EDP',['玫瑰','荔枝','洋甘菊'],1,1,[3,2,3,2],'午后约会 · 花园散步','像一束仍带着绿叶的玫瑰，鲜活里藏一点俏皮。','https://www.diptyqueparis.com/en_us/p/eau-de-parfum-eau-rose-75ml.html','niche'],
['JO MALONE LONDON','英国梨与小苍兰','English Pear & Freesia Cologne',['威廉梨','小苍兰','广藿香'],1,1,[3,2,3,2],'日常通勤 · 周末午餐','像果园里刚好的熟梨，轻盈而不失柔和暖意。','https://www.jomalone.co.uk/product/25946/12553/Scents/english-pear-freesia-Scent','designer'],
['MAISON MARGIELA','慵懒周日','REPLICA Lazy Sunday Morning EDT',['铃兰','鸢尾','白麝香'],3,1,[3,3,2,2],'室内工作 · 慢节奏周末','像干净床单上散着晨光，亲近、柔软又自在。','https://www.maisonmargiela-fragrances.us/replica-memory-box/3614273668811.html','designer'],
['DIPTYQUE','檀道','Tam Dao EDP',['檀香','雪松','柏树'],2,0,[2,1,3,3],'独处阅读 · 安静通勤','像推开一扇木门，干燥木香让思绪慢下来。','https://www.diptyqueparis.com/en_us/l/fragrances.html','niche'],
['MAISON MARGIELA','壁炉火光','REPLICA By the Fireplace EDT',['栗子','愈创木','香草'],3,3,[0,0,3,3],'寒冷夜晚 · 休闲聚会','烤栗子的甜暖裹着木烟，像炉火旁的一条毯子。','https://www.maisonmargiela-fragrances.eu/en_GB/layering-replica-memories/layering-replica-memories.html','designer'],
['MAISON MARGIELA','爵士酒廊','REPLICA Jazz Club EDT',['粉红胡椒','朗姆酒','烟草叶'],2,2,[0,0,3,3],'夜间约会 · 秋冬聚会','微醺的暖意与烟草交织，像一段慢下来的低音。','https://www.maisonmargiela-fragrances.eu/en_GB/layering-replica-memories/layering-replica-memories.html','designer'],
['DIPTYQUE','檀道','Tam Dao EDT',['檀香','雪松','柏树'],2,0,[2,2,3,3],'工作日 · 林间散步','安静木质带着清爽树影，像一封不急着读完的信。','https://www.diptyqueparis.com/en_us/l/fragrances.html','niche']
];
perfumes.push(...expandedPerfumes);
let season=null,step=0,answers=[],view='home';const app=document.getElementById('app');
function render(){app.className='fade';void app.offsetWidth;if(view==='home')renderHome();else if(view==='quiz')renderQuiz();else renderResult();}
function reset(){view='home';season=null;answers=[];step=0;document.documentElement.style.setProperty('--accent','#687e63');render();window.scrollTo(0,0)}
function start(s){if(!Number.isInteger(s)||s<0||s>3)throw Error('请选择有效季节');season=s;answers=[];step=0;view='quiz';document.documentElement.style.setProperty('--accent',seasons[s].accent);document.documentElement.style.setProperty('--tint',seasons[s].tint);render();window.scrollTo(0,0)}
function renderHome(){app.innerHTML=`<section class="intro"><h1>这个季节的你是什么味道的？</h1><p class="subtitle">把你对季节的感受，变成属于你的气味</p></section><div class="seasons">${seasons.map((s,i)=>`<button class="season" data-season="${i}" aria-label="选择${s.name}，开始测试"><div class="art s${i}" role="img" aria-label="${s.name}蜡笔插画"></div><h2>${s.name}<small>${s.en}</small></h2></button>`).join('')}</div><p class="tiny-note">8 个小问题 · 约 2 分钟</p>`;app.querySelectorAll('[data-season]').forEach(b=>b.onclick=()=>start(+b.dataset.season));}
function choose(a){if(view!=='quiz'||!Number.isInteger(a)||a<0||a>3)throw Error('请选择当前问题的有效选项');answers[step]=a;render()}
function next(){if(answers[step]===undefined)throw Error('请先选择一个答案');if(step===7)view='result';else step++;render();window.scrollTo(0,0)}
function renderQuiz(){const q=questions[step];app.innerHTML=`<section class="quiz"><div class="quiz-top"><button class="text-button" id="back">←︎ ${step?'上一题':'重选季节'}</button><span class="badge">${seasons[season].name}香笺</span><span>${String(step+1).padStart(2,'0')} / 08</span></div><div class="progress" role="progressbar" aria-label="测试进度" aria-valuenow="${step+1}" aria-valuemin="0" aria-valuemax="8"><div style="width:${(step+1)/8*100}%"></div></div><div class="question-icon">${questionIcon(q[2])}</div><h1>${q[0]}</h1><p class="question-caption">${q[1]}</p><div class="answers">${q[3].map((a,i)=>`<button class="answer ${answers[step]===i?'selected':''}" aria-pressed="${answers[step]===i}" data-answer="${i}"><span class="letter">${'ABCD'[i]}</span>${a}</button>`).join('')}</div><div class="quiz-bottom"><span class="tiny-note">${step<6?'跟着直觉，不用想太久':'让推荐更贴近你的鼻子'}</span><button class="primary" id="next" ${answers[step]===undefined?'disabled':''}>${step===7?'打开我的香笺':'下一题'} →︎</button></div></section>`;app.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>choose(+b.dataset.answer));document.getElementById('next').onclick=next;document.getElementById('back').onclick=()=>{if(step){step--;render()}else reset()};}
function resultData(){const scores=[0,0,0,0];answers.slice(0,6).forEach(a=>scores[a]++);scores[answers[6]]+=2;const type=scores.indexOf(Math.max(...scores));const sweet=answers[7];const seed=answers.reduce((n,a)=>n*5+a+1,season+1);const ranked=perfumes.map((p,i)=>({p,i,score:p[6][season]*3+(p[4]===answers[6]?6:0)+(p[4]===type?3:0)-Math.abs(p[5]-sweet)*3,tie:((seed^(i*2654435761))>>>0)%1000})).filter(x=>x.p[6][season]>0&&!(sweet===0&&x.p[5]>1)).sort((a,b)=>b.score-a.score||a.tie-b.tie);const picked=[];for(const x of ranked){if(picked.some(y=>y.p[0]===x.p[0]))continue;picked.push(x);if(picked.length===4)break}for(const cat of ['niche','designer']){if(!picked.some(x=>x.p[10]===cat)){const x=ranked.find(x=>x.p[10]===cat&&!picked.some(y=>y.p[0]===x.p[0]));if(x)picked[3]=x}}picked.sort((a,b)=>b.score-a.score);return{type,picks:picked.map(x=>x.p)}}
function renderResult(){const r=resultData(),p=profiles[r.type],s=seasons[season];app.innerHTML=`<div class="result-top"><button class="text-button" id="change">←︎ 重选季节</button><span class="result-season">${s.en} / ${s.name}</span></div><section class="persona"><div class="persona-art art s${season}" aria-hidden="true"></div><div class="persona-content"><span class="persona-label">你的当季香气人格</span><div class="persona-code">${p.code}</div><h1>${p.name}</h1><p class="persona-line">${p.desc}</p><div class="persona-tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div></div></section><details class="match-details"><summary>为什么是这份香气？<span>＋</span></summary><p>${s.reason}</p><p>也参考了你的香味与甜度偏好。人设与季节搭配是趣味选香灵感，不是心理测评。</p></details><div class="scent-heading"><h2>你的当季香水</h2><span>4 支，4 种相遇</span></div><div class="scent-grid">${r.picks.map((f,i)=>`<article class="scent-card" style="--delay:${i*90}ms"><div class="scent-card-top"><span class="scent-rank">0${i+1}</span><span class="scent-pick">${i===0?'首选香气':'另一种可能'}</span></div><div class="scent-brand">${f[0]}</div><h3>${f[1]}</h3><div class="scent-english">${f[2]}</div><div class="scent-notes">${f[3].join(' · ')}</div><p class="scent-mood">${f[8]}</p><details class="scent-more"><summary>场景与详情 <span>＋</span></summary><div><p>${f[7]}</p><a class="source" href="${f[9]}" target="_blank" rel="noopener noreferrer">查看香调资料 ↗︎</a></div></details></article>`).join('')}</div><div class="result-end"><button class="text-button" id="retry">再遇见另一面的自己 ↻︎</button><details class="pool-note"><summary>关于推荐</summary><p>从 ${new Set(perfumes.map(p=>p[0])).size} 个品牌、${perfumes.length} 支香水中匹配。香调参考品牌、零售商及香水资料库；季节、场景与甜度为编辑判断。丝芙兰资料来自不同地区，非本地库存保证。建议先试香。</p></details></div>`;document.getElementById('change').onclick=reset;document.getElementById('retry').onclick=()=>start(season);}

document.getElementById('home').onclick=reset;render();
if(document.modelContext?.registerTool){for(const tool of [{name:'start_season_quiz',description:'选择季节并开始八题选香测试',inputSchema:{type:'object',properties:{season:{type:'integer',minimum:0,maximum:3}},required:['season'],additionalProperties:false},execute:({season})=>{start(season);return{question:questions[step][0],options:questions[step][3]}}},{name:'answer_scent_question',description:'回答当前问题并进入下一题，末题显示推荐',inputSchema:{type:'object',properties:{answer:{type:'integer',minimum:0,maximum:3}},required:['answer'],additionalProperties:false},execute:({answer})=>{choose(answer);next();return view==='result'?{personality:profiles[resultData().type].name,recommendations:resultData().picks.map(p=>p[2])}:{question:questions[step][0],options:questions[step][3]}}}]){try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{})}catch{}}}
