// Notes are sourced from linked brand/retailer pages. Seasonal fit, family and sweetness are editorial matching fields.
const expandedPerfumes = [
['CHANEL','邂逅柔情','Chance Eau Tendre EDT',['葡萄柚','茉莉','白麝香'],1,1,[3,3,2,1],'日常 · 约会','轻盈果香里，藏着一束柔软白花。','https://www.chanel.com/il-en/fragrance/p/126320/chance-eau-tendre-eau-de-toilette-spray/','designer'],
['DIOR','迪奥小姐花漾甜心','Miss Dior Blooming Bouquet EDT',['牡丹','大马士革玫瑰','白麝香'],1,1,[3,2,2,1],'春游 · 午后约会','像刚收到的一束花，清透而温柔。','https://www.dior.com/en_gb/beauty/products/miss-dior-blooming-bouquet-C099700102.html','designer'],
['GUERLAIN','柑橘罗勒','Aqua Allegoria Mandarine Basilic EDT',['柑橘','罗勒','绿茶'],0,0,[3,3,2,1],'旅行 · 日间通勤','剥开柑橘的瞬间，草本绿意一同散开。','https://www.guerlain.com/sg/en-sg/p/aqua-allegoria-mandarine-basilic---eau-de-toilette-P014394.html','designer'],
['TOM FORD','橙花之水','Neroli Portofino EDP',['橙花','佛手柑','黄柑橘'],0,0,[3,3,2,1],'海边 · 度假','明亮橙花像海岸清晨晒过的白衬衫。','https://www.tomfordbeauty.com/product/neroli-portofino-eau-de-parfum','designer'],
['PRADA','鸢尾精粹','Infusion d’Iris EDP',['鸢尾','橙花','柑橘'],1,0,[3,2,3,2],'工作日 · 看展','柔软粉感留在衣角，克制又安静。','https://www.prada-beauty.com/fragrance/les-infusions/infusion-diris-eau-de-parfum/MPL01370.html','designer'],
['YVES SAINT LAURENT','自由之水','Libre EDP',['薰衣草','橙花','麝香'],1,2,[2,1,3,3],'晚餐 · 正式场合','花香与草本碰撞，温柔里有自己的主张。','https://www.sephora.com/product/libre-eau-de-parfum-P448102','designer'],
['GUCCI','绽放香精','Bloom Parfum',['珊瑚茉莉','甜苔藓','秘鲁香脂'],1,2,[2,1,3,3],'夜间约会 · 聚会','浓郁花香被温暖香脂轻轻托住。','https://www.sephora.com/product/gucci-bloom-parfum-P516066','designer'],
['VALENTINO','生于罗马女士','Donna Born in Roma EDP',['黑醋栗','茉莉','波旁香草'],1,2,[2,1,3,3],'约会 · 城市夜游','鲜活果香与暖香草，像傍晚亮起的街灯。','https://www.sephora.com/product/born-in-roma-P449116','designer'],
['BURBERRY','她','Her EDP',['黑醋栗','茉莉','白木'],1,2,[3,1,3,2],'周末 · 朋友聚会','浆果的甜意里，有轻快的城市步调。','https://www.sephora.com/product/her-eau-de-parfum-P437631','designer'],
['VERSACE','狄伦紫','Dylan Purple EDP',['苦橙','小苍兰','雪松'],0,1,[3,3,2,1],'日常 · 夏日出游','明亮果香与花瓣相遇，轻松又有活力。','https://www.sephora.com/product/versace-dylan-purple-eau-de-parfum-P504912','designer'],
['KAYALI','香草 28','Vanilla | 28 EDP',['香草','零陵香豆','琥珀木'],3,3,[1,0,3,3],'冷天 · 晚间约会','像温热甜点的第一口，柔软而绵长。','https://www.sephora.com/product/kayali-vanilla-P439406','niche'],
['CLEAN RESERVE','肌肤','Skin EDP',['麝香','古巴香脂','咸果仁糖'],3,1,[3,2,3,3],'室内工作 · 独处','若有似无的甜暖，像刚穿上的软棉衣。','https://www.sephora.com/brand/clean-reserve?sortBy=BEST_SELLING','niche'],
['CLEAN RESERVE','雨','Rain EDP',['佛手柑','白花','香根草'],0,0,[3,3,2,1],'雨天 · 日间散步','雨后空气里的清亮水意。','https://www.sephora.com/brand/clean-reserve?sortBy=BEST_SELLING','niche'],
['CLEAN RESERVE','光耀花蜜','Radiant Nectar EDP',['黄葵籽','梨花蜜','麝香'],0,2,[3,3,2,1],'周末 · 户外午餐','一口梨的甜润，化在明亮空气里。','https://www.sephora.com/brand/clean-reserve?sortBy=BEST_SELLING','niche'],
['THE 7 VIRTUES','香草森林','Vanilla Woods EDP',['梨','玫瑰','香草'],3,3,[1,0,3,3],'秋冬 · 慢节奏夜晚','香草暖意里有果香与花香，像柔软的拥抱。','https://www.sephora.com/product/vanilla-woods-eau-de-parfum-P428713','niche'],
['PHLUR','思念之人','Missing Person EDP',['白麝香','茉莉','橙花'],3,1,[3,2,3,3],'日常 · 亲密约会','像留在毛衣上的熟悉气味，安静贴近。','https://phlur.com/products/missing-person-100ml','niche'],
['GLOSSIER','你','You EDP',['粉红胡椒','鸢尾','Ambrox'],3,0,[3,3,3,3],'通勤 · 日常','柔和的肌肤气息，加一点细微辛香。','https://www.sephora.com/product/glossier-glossier-you-eau-de-parfum-P504364','niche'],
['COMMODITY','牛奶 · 浓郁版','Milk+ Bold EDP',['木柴','桃花心木','棉花糖'],3,3,[0,0,3,3],'冷夜 · 居家','木头的暖与棉花糖的甜，慢慢融在一起。','https://www.sephora.com/product/milk-bold-P502315','niche'],
['ELLIS BROOKLYN','神话','MYTH EDP',['黄葵籽','茉莉花瓣','麝香'],3,1,[3,2,3,2],'工作日 · 阅读','轻柔花瓣与干净麝香，像衣领上的小秘密。','https://www.sephora.com/product/myth-eau-de-parfum-P412047','niche'],
['JULIETTE HAS A GUN','非香水','Not a Perfume EDP',['Cetalox','琥珀感','麝香感'],3,0,[3,3,3,3],'日常 · 安静空间','低声的琥珀肌肤感，留出自己的余地。','https://us.juliettehasagun.com/pages/not-a-perfume','niche'],
['AESOP','悟','Tacit EDP',['柚子','罗勒','香根草'],0,0,[3,3,3,1],'通勤 · 城市散步','柑橘划开草本绿意，像清醒的一口空气。','https://www.aesop.com/c/fragrance/tacit/','niche'],
['NONFICTION','檀香奶油','Santal Cream EDP',['檀香','香根草','小豆蔻'],2,1,[2,1,3,3],'独处 · 咖啡馆','柔和木质包住细小辛香，安静而有温度。','https://int.nonfiction.com/products/santal-cream-parfum','niche'],
['TAMBURINS','洋甘菊','CHAMO EDP',['洋甘菊','快乐鼠尾草','木质感'],3,2,[3,1,3,3],'周末 · 慢节奏约会','带蜜感的草本，像晒过太阳的柔软午后。','https://www.tamburins.com/en/item/1662462471/','niche'],
['J-SCENT','和肌','Yawahada EDP',['梨','米粉','檀香'],3,1,[3,2,3,3],'室内 · 安静约会','米粉与柔和奶感，像贴近肌肤的薄纱。','https://j-scent-global.com/products/yawahada','niche'],
['SHOLAYERED','清新梨','Fresh Pear Non-Alcohol Perfume',['梨','清透果香'],0,1,[3,3,2,1],'日常 · 轻松出游','一颗刚熟的梨，清甜而通透。','https://sholayered.com/products/non-alcohol-perfume-fresh-pear','niche'],
['LE LABO','末茶 26','Thé Matcha 26 EDP',['抹茶意象','无花果','雪松'],2,1,[3,2,3,3],'阅读 · 独处','细腻无花果与木质，像只留给自己的安静时刻。','https://www.lelabofragrances.com.au/th-matcha-26-1186.html','niche'],
['BYREDO','非洲之旅','Bal d’Afrique EDP',['佛手柑','万寿菊','黑醋栗'],0,1,[3,3,3,2],'旅行 · 周末','明亮花果气息，带着轻快的节奏。','https://www.byredo.com/uk_en/p/bal-d-afrique-eau-de-parfum?sku=0065212491','niche'],
['SHAY & BLUE','海盐焦糖','Salt Caramel EDP',['焦糖','海盐','檀香'],3,3,[1,0,3,3],'寒冷日子 · 休闲聚会','甜与咸交织，像一小块暖心的焦糖。','https://us.shayandblue.com/products/salt-caramel-fragrance-100ml','niche'],
['IMAGINARY AUTHORS','圣朱利普','Saint Julep EDP',['甜薄荷','橘子','波旁酒'],0,2,[2,3,2,1],'夏夜 · 度假','薄荷甜意里有微醺的松弛。','https://imaginaryauthors.com/products/saint-julep','niche'],
['宋朝 SONG CHAO','木歌','Mu Ge',['葡萄柚','燧石','雪松'],2,0,[2,2,3,3],'日常 · 独处','清苦果皮与干燥木质，像风吹过石头与树林。','https://www.fragrantica.com/perfume/Song-Chao-song-chao-xiang-fen/Mu-Ge-mu-ge-115891.html','niche'],
['宋朝 SONG CHAO','东方木兰','Oriental Magnolia',['绿叶','木兰','白松香'],1,1,[3,2,2,1],'春日出游 · 约会','绿叶托着洁净白花，轻盈又鲜活。','https://www.fragrantica.com/perfume/Song-Chao-song-chao-xiang-fen/Oriental-Magnolia-dong-fang-mu-lan-115888.html','niche']
];
